mapmatching.osrm.url=http://router.project-osrm.org/match/v1/driving/
mapmatching.overpass.url=https://overpass-api.de/api/interpreter

mapmatching.hmm.sigma=4.07
mapmatching.hmm.beta=10.0
mapmatching.hmm.search-radius=50.0